import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Form, Button, Card, Row, Col } from "react-bootstrap";
import { Header, Loader } from "../src/components";
import styles from "../styles/AddStaff.module.css";
import useCustomer from "../src/hooks/useCustomer";

type formData = {
  _id: string;
  email: string;
  phone: string;
  address: string;
  firstName: string;
  lastName: string;
  cylinderSize: string;
  cylinderAge: string;
  dob: string;
};

const AddCustomer: NextPage = () => {
  const [formInput, setFormInput] = useState<formData>({
    _id: "RETITRT59dsd",
    email: "",
    phone: "",
    address: "",
    firstName: "",
    lastName: "",
    cylinderSize: "",
    cylinderAge: "",
    dob: "",
  });
  const {
    _id,
    email,
    phone,
    address,
    lastName,
    firstName,
    dob,
    cylinderAge,
    cylinderSize,
  } = formInput;

  const onChangeHandler = (e: any) => {
    setFormInput({ ...formInput, [e.target.name]: e.target.value });
  };

  const { addCustomer, loading } = useCustomer();
  const onSubmit = (e: any) => {
    e.preventDefault();
    addCustomer(formInput);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {loading && <Loader />}
      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
            <Card.Title>
                <b>Add Customer</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              <Row>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="text"
                      placeholder="First Name"
                      name="firstName"
                      value={firstName}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="text"
                      placeholder="Last Name"
                      name="lastName"
                      value={lastName}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="number"
                      placeholder="Phone"
                      name="phone"
                      value={phone}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="text"
                      placeholder="Address"
                      name="address"
                      value={address}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="email"
                      placeholder="Email"
                      name="email"
                      value={email}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="date"
                      placeholder="DOB"
                      name="dob"
                      value={dob}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="number"
                      placeholder="Cylinder Age"
                      name="cylinderAge"
                      min="1"
                      value={cylinderAge}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>
                <Col sm={12} md={4}>
                  <Form.Group className="mb-5 mt-3" controlId="formBasicEmail">
                    <Form.Control
                      className="form"
                      type="number"
                      placeholder="Cylinder Size"
                      name="cylinderSize"
                      min="1"
                      value={cylinderSize}
                      onChange={(e) => onChangeHandler(e)}
                    />
                  </Form.Group>
                </Col>

                <Col sm={12} md={4}>
                  <div style={{ float: "right" }}>
                    <Button
                      className="mb-5 mt-3"
                      variant="primary"
                      onClick={onSubmit}
                    >
                      Add Customer
                    </Button>
                  </div>
                </Col>
              </Row>
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default AddCustomer;
