import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Login.module.css";
import { Button, Card } from "react-bootstrap";
import { Header, Loader } from "../src/components";
import QRCode from "react-qr-code";
import domtoimage from "dom-to-image";
import { saveAs } from "file-saver";
import useCreateId from "../src/hooks/useCreateId";
import withAuth from "../src/hoc/withAuth";

const Home: NextPage = () => {
  const { uid, createId, setUid } = useCreateId();

  const downloadHandler = (event: any) => {
    event.preventDefault();
    let doc : any = document.getElementById("qr-code")
    domtoimage
      .toBlob(doc)
      .then((blob) => {
        saveAs(blob, `${uid}`);
      });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
              <Card.Title>
                <b>Create Code</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              {uid.length > 2 ? (
                <div className="text-center">
                  <div
                    id="qr-code"
                    style={{
                      backgroundColor: "#ffffff",
                      paddingTop: "20px",
                      paddingBottom: "20px",
                    }}
                  >
                    <QRCode value={uid} />
                  </div>

                  <div className="btn-group" role="group">
                    <Button
                      className="mb-3 mt-3 pr-2"
                      variant="danger"
                      onClick={() => setUid("")}
                    >
                      Clear
                    </Button>
                    <Button
                      className="mb-3 mt-3 ml-3"
                      variant="success"
                      onClick={downloadHandler}
                    >
                      Download
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="text-center">
                  <Button
                    className="mb-3 mt-3"
                    variant="primary"
                    onClick={createId}
                  >
                    Generate new QR code
                  </Button>
                </div>
              )}
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default withAuth(Home, true);
