import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Login.module.css";
import { Button, Card } from "react-bootstrap";
import { Header, Loader } from "../src/components";
import QRCode from "react-qr-code";
import domtoimage from "dom-to-image";
import { saveAs } from "file-saver";

const Home: NextPage = () => {
  const [id, setId] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  const onCreateId = () => {
    setId("uyjklpiouu");
  };

  const downloadHandler = (event: any) => {
    event.preventDefault();
    domtoimage.toBlob(document.getElementById("qr-code", {width: 1080, height: 1080})).then((blob) => {
      saveAs(blob, `${id}`);
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {loading && <Loader />}
      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
              <Card.Title>
                <b>Create Code</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              {id.length > 2 ? (
                <div className="text-center">
                  <div id="qr-code" style={{backgroundColor: "#ffffff", paddingTop: "20px", paddingBottom: "20px"}}>
                    <QRCode value={id} />
                  </div>

                  <div className="btn-group" role="group">
                    <Button
                      className="mb-3 mt-3 pr-2"
                      variant="danger"
                      onClick={() => setId("")}
                    >
                      Clear
                    </Button>
                    <Button
                      className="mb-3 mt-3 ml-3"
                      variant="success"
                      onClick={downloadHandler}
                    >
                      Download
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="text-center">
                  <Button
                    className="mb-3 mt-3"
                    variant="primary"
                    onClick={onCreateId}
                  >
                    Generate new QR code
                  </Button>
                </div>
              )}
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default Home;
