import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Login.module.css";
import { Button, Card } from "react-bootstrap";
import { Header, Loader } from "../src/components";
import useCustomer from "../src/hooks/useCustomer";

const Customers: NextPage = () => {
  const { getAllCustomer, customerData } = useCustomer();
  console.log(customerData);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
              <Card.Title>
                <b>Create Code</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              <div className="text-center">
                <Button
                  className="mb-3 mt-3"
                  variant="primary"
                  onClick={() => getAllCustomer()}
                >
                  get users
                </Button>
              </div>
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default Customers;
