import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Form, Button, Card, Row, Col } from "react-bootstrap";
import { Header, Loader, CustomerModal } from "../src/components";
import useStaff from "../src/hooks/useStaff";
import styles from "../styles/AddStaff.module.css";
import useCustomer from "../src/hooks/useCustomer";

const send_mail = () => {
  const { loading, customerData, getAllCustomer } = useCustomer();
  const { senBulKMails } = useStaff();
  const [formInput, setFormInput] = useState({
    emails: undefined,
    message: "",
    subject: "",
  });
  const { message, subject } = formInput;

  const onChangeHandler = (e: any) => {
    setFormInput({ ...formInput, [e.target.name]: e.target.value });
  };

  const onSubmit = (e: any) => {
    e.preventDefault();
    senBulKMails(formInput)
  };

  console.log(formInput);
  useEffect(() => {
    getAllCustomer();
  }, []);

  useEffect(() => {
    let data: any = customerData.map((data: any) => data.email);
    let val: any = [];
    val.push(data);
    setFormInput({ ...formInput, emails: val });
  }, [customerData]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {loading && <Loader />}
      <CustomerModal />
      <div className={styles.container}>
        <main className={styles.main}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
              <Card.Title>
                <b>Send Bulk Emails</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              <div>
                <Row>
                  <Col sm={12}>
                    <Form.Group
                      className="mb-5 mt-3"
                      controlId="formBasicEmail"
                    >
                      <Form.Label>Subject</Form.Label>
                      <Form.Control
                        className="form"
                        type="text"
                        placeholder="Enter Email subject"
                        name="subject"
                        value={subject}
                        onChange={(e) => onChangeHandler(e)}
                      />
                    </Form.Group>
                  </Col>

                  <Col sm={12}>
                    <Form.Group
                      className="mb-5 mt-3"
                      controlId="formBasicEmail"
                    >
                      <Form.Label>Type message</Form.Label>
                      <Form.Control
                        as="textarea"
                        rows={5}
                        className="form"
                        type="text"
                        name="message"
                        value={message}
                        onChange={(e) => onChangeHandler(e)}
                      />
                    </Form.Group>
                  </Col>

                  <Col sm={12}>
                    <div className="text-center">
                      <Button
                        className="mb-5 mt-3"
                        variant="primary"
                        onClick={onSubmit}
                      >
                        Send Now
                      </Button>
                    </div>
                  </Col>
                </Row>
              </div>
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default send_mail;
