import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Login.module.css";
import {
  Card,
  InputGroup,
  SplitButton,
  Dropdown,
  FormControl,
} from "react-bootstrap";
import { Header, Loader } from "../src/components";
import useStaff from "../src/hooks/useStaff";
import withAuth from "../src/hoc/withAuth";

const Staff: NextPage = () => {
  const [query, setQuery] = useState({
    name: "",
    keyword: "",
  });
  const { getAllStaffs,
    fillerStaff, staffsData, loading } = useStaff();

  useEffect(() => {
    getAllStaffs();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {loading && <Loader />}
      <div className={styles.container}>
        <main style={{ marginTop: "50px" }}>
          <Card className="shadow-sm p-3 mb-5 bg-body rounde">
            <Card.Header>
              <Card.Title>
                <b>Staffs</b>
              </Card.Title>
            </Card.Header>
            <Card.Body>
              <div>
                <InputGroup className="shadow-lg mb-5 mt-3">
                  <SplitButton
                    variant="primary"
                    title="Apply"
                    id="segmented-button-dropdown-1"
                    onClick={() => fillerStaff(query)}
                  >
                    <Dropdown.Item
                      onClick={() => setQuery({ ...query, name: "_id" })}
                    >
                      By Id
                    </Dropdown.Item>
                    <Dropdown.Divider />
                    <Dropdown.Item
                      onClick={() => setQuery({ ...query, name: "email" })}
                    >
                      By Email
                    </Dropdown.Item>
                  </SplitButton>
                  <FormControl
                    type="text"
                    onChange={(e: any) =>
                      setQuery({ ...query, keyword: e.target.value })
                    }
                    aria-label="Text input with dropdown button"
                  />
                </InputGroup>
              </div>
              <div className="table-responsive">
                <table className="table table-striped">
                  <thead>
                    <tr style={{ width: "100%", fontSize: "13px" }}>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Email</th>
                      <th>Address</th>
                      <th>Phone</th>
                      <th>Role</th>
                    </tr>
                  </thead>
                  <tbody>
                    {staffsData[0] !== null
                      ? staffsData?.map((data: any) => (
                          <tr style={{ fontSize: "13px" }} key={data?._id}>
                            <td>{data?.firstName}</td>
                            <td>{data?.lastName}</td>
                            <td>{data?.email}</td>
                            <td>{data?.address}</td>
                            <td>{data?.phone}</td>
                            <td>{data?.role}</td>
                          </tr>
                        ))
                      : null}
                  </tbody>
                </table>
              </div>

              <div className="text-center"></div>
            </Card.Body>
          </Card>
        </main>
      </div>
    </div>
  );
};

export default withAuth(Staff, true);
